# source: 
# 
# zf181003.1516

version: '3'

services:
    dev:
        build: .
        image: zubuntu
        container_name: dev
        volumes:
            - .:/myubuntu
        ports:
            - "5221:22"
        stdin_open: true
        tty: true

    test:
        image: zubuntu
        container_name: test
        ports:
        - "5222:22"
        stdin_open: true
        tty: true

    master:
        image: zubuntu
        container_name: master
        ports:
        - "5223:22"
        stdin_open: true
        tty: true

    user1:
        image: zubuntu
        container_name: user1
        ports:
        - "5224:22"
        stdin_open: true
        tty: true

    user2:
        image: zubuntu
        container_name: user2

        ports:
        - "5225:22"
        stdin_open: true
        tty: true

    user3:
        image: zubuntu
        container_name: user3
        ports:
        - "5226:22"
        stdin_open: true
        tty: true

