version: '3'
services:

    lighttpd:
        #https://hub.docker.com/r/sebp/lighttpd/
        image: sebp/lighttpd
        volumes:
            - $PWD:/var/www/localhost/htdocs
        ports:
            - "8080:80"
        tty: true
        restart: always


